sonar.projectKey=valeriy42_ml-cpp
sonar.projectName=C SQ-Scanner-based project analyzed on SonarCloud using sonar-scanner
sonar.projectVersion=1.0

# =====================================================
#   Meta-data for the project
# =====================================================

sonar.links.homepage=https://github.com/valeriy42/ml-cpp
; sonar.links.ci=https://travis-ci.org/SonarSource/sq-com_example_c-sqscanner-travis
sonar.links.scm=https://github.com/valeriy42/ml-cpp
sonar.links.issue=https://github.com/valeriy42/ml-cpp/issues

sonar.login=9162344b1a706b87b25d3ad1282f0fe3929467cd
sonar.organization=valeriy42-github


# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================

# SQ standard properties
sonar.sources=lib,bin,include
; sonar.sources=include
sonar.languages=c++
sonar.sourceEncoding=UTF-8


# Properties specific to the C/C++ analyzer:
sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.gcov.reportsPath=.
sonar.cfamily.threads=10
